<?php

namespace AppBundle\Repository;

/**
 * CmsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsRepository extends \Doctrine\ORM\EntityRepository
{
}
